### ISSUE TITLE
[Suggestion] New rule: jsx-no-literal-object

### ISSUE THREAD

**Issue by jeanbenitez** [palantir/tslint-react#191] opened 2018-12-19 15:07 UTC
I think can be a bad practice pass an object literal via jsx prop in render, because the render will make a new object every time.

ex.:

```
<my-component user={{ userId: 1234 }} />
```

Thanks!

**Comment by adidahiya** [comment] 2019-03-12 22:21
duplicate of #89

**Closed by adidahiya** 2019-03-12 22:21 UTC
