### ISSUE TITLE
jsx-alignment is slightly incompatible with VS Code auto-format

### ISSUE THREAD

**Issue by punya-asapp** [palantir/tslint-react#62] opened 2017-01-20 22:43 UTC
VS Code's auto-format yields

```tsx
          <AutosizeInput
            onChange={onNameChange}
            placeholder="Name your project"
            placeholderIsMinWidth={true}
            value={props.name}
            />
```

But `jsx-alignment` wants

```tsx
          <AutosizeInput
            onChange={onNameChange}
            placeholder="Name your project"
            placeholderIsMinWidth={true}
            value={props.name}
          />
```

Note that the last line is off by $indent spaces.

Is there a way to configure either VS Code or TSLint to make the two match up? I don't have a preference about which of the two conventions gets used.

Thanks for your time!

**Comment by lvillani** [comment] 2017-04-11 08:51
@punya-asapp I think this is no longer the case with the latest versions of VSCode. I'm using 1.11.1 and if I put the closing tag aligned with the left angle bracket it stays there even if I manually trigger a format action.

(Btw, I believe that this is not a bug in tslint-react itself but in the editor instead).

**Comment by punya-asapp** [comment] 2017-04-11 13:16
Thanks for looking into it, and please feel free to close out the ticket.

**Closed** 2017-04-11 15:58 UTC
